Vishnya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from orders.views import my_webhook_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("structure.urls", namespace='structure')),
    path('users/', include("users.urls", namespace='users')),
    path('orders/', include("orders.urls", namespace='orders')),
    path('webhook/yookassa/', my_webhook_handler, name='webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import OrderView, SuccessTemplateView, CancelTemplateView, OrderListView, order_remove, receipt_list_view

app_name = 'order'
urlpatterns = [
    path('', OrderView.as_view(), name='order_view'),
    path('success/', SuccessTemplateView.as_view(), name='success_order'),
    path('canсel/', CancelTemplateView.as_view(), name='cancel_order'),
    path('list/', OrderListView.as_view(), name='list_order'),
    path('list/remove/<int:id>', order_remove, name='order_remove'),
    path('receipt/<int:id>', receipt_list_view, name='receipt'),
]

structure/urls.py
from django.urls import path
from structure.views import *

app_name = 'structure'
urlpatterns = [
    path('', index, name='index'),
    path('collections/', collections, name='collections'),
    path('sub_collection/<str:collection_name>/', universal_collect, name='universal_collect'),
    path('by_year/<str:year_name>/',universal_year, name='universal_year'),
    path('art_instance/<str:art_name>/', artpiece, name='artpiece'),
    path('about/', bio, name='bio'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/view/', basket_view, name='basket_view'),
    path('baskets/remove/<int:id>/', basket_remove, name='basket_remove'),
]

users/urls.py
from users.views import UserRegistrationView, UserLoginView, logout_view, UserProfileView
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
]

structure/models.py
from django.db import models

from users.models import User


# Create your models here.
class Collection(models.Model):
    name = models.CharField(max_length=128,unique=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='collections_imgs')

    def __str__(self):
        return self.name


class Year(models.Model):
    year = models.CharField(max_length=4, unique=True)

    def __str__(self):
        return self.year


class Artwork(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    collection = models.ForeignKey(to=Collection, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='artworks_imgs')
    year = models.ForeignKey(to=Year, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=1000)

    def __str__(self):
        return f"Name:{self.name}; Collection:{self.collection}; Year:{self.year}"

    def purchase_statistics(self):
        from orders.models import Order  # Импортируем модель Order
        orders = Order.objects.filter(status__in=[1, 2])  # Только оплаченные и доставленные заказы
        total_purchased = 0

        for order in orders:
            for item in order.basket_history.get('purchased_items', []):
                if item['product_name'] == self.name:
                    total_purchased += item['quantity']

        return {
            "total_purchased": total_purchased,
            "total_revenue": total_purchased * self.price
        }


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def for_user(self, user):
        return self.filter(user=user)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Artwork, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    objects = BasketQuerySet.as_manager()
    comment = models.TextField(default="")

    def __str__(self):
        return f'{self.user} basket'

    def sum(self):
        return self.quantity * self.product.price

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': self.sum()
        }
        return basket_item

structure/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from structure import models
from structure.models import Basket, Artwork
from users.models import User


# Create your views here.
def index(request):
    context = {
        'title': 'Soya Mariya Designer',
        'artworks1': models.Artwork.objects.all()[::3],
        'artworks2': models.Artwork.objects.all()[1::3],
        'artworks3': models.Artwork.objects.all()[2::3],
    }
    return render(request, 'structure/index.html', context )


def collections(request):
    context = {
        'title': 'Collection',
        'collections': models.Collection.objects.all()
    }
    return render(request, 'structure/collections.html', context)


def bio(request):
    context = { 'title': 'About me'}
    return render(request, 'structure/bio.html', context)


def universal_collect(request,collection_name):
    collection_id = models.Collection.objects.get(name=collection_name)
    sub_collection =  models.Artwork.objects.filter(collection=collection_id)
    return render(request, 'structure/universal_collect.html', {'result': sub_collection, 'collection': collection_name, 'title': collection_name})


def universal_year(request, year_name):
    year_id = models.Year.objects.get(year=year_name)
    by_year = models.Artwork.objects.filter(year=year_id)
    return render(request, 'structure/universal_year.html', {'result': by_year, 'year': year_name, 'title':year_name})


def artpiece(request, art_name):
    art_instance = get_object_or_404(models.Artwork, name=art_name)
    return render(request, 'structure/art.html', {'result': art_instance, 'art': art_name,'title': art_name })


def basket_add(request, product_id):
    artwork = Artwork.objects.get(id=product_id)
    user = User.objects.get(username=request.user)
    baskets = Basket.objects.filter(user=user, product=artwork)

    if not baskets.exists():
        Basket.objects.create(user=user, product=artwork, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_view(request):
    user = User.objects.get(username=request.user)
    context = {
        'baskets': Basket.objects.filter(user=user),
    }
    return render(request, 'structure/basket.html', context)


def basket_remove(request, id):
    basket = Basket.objects.get(pk=id)
    if basket.quantity == 1:
        basket.delete()
    else:
        basket.quantity -= 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

structure/templates/structure/art.html
{% extends 'structure/base.html' %}
{% load static %}

{% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% endblock %}

{% block content %}
<div class="single-art-page">
  <img class="single-image"src="{{result.image.url}}">

    <a href="{% url 'structure:basket_add' result.id %}" class="helvetic-pale">ДОБАВИТЬ В КОРЗИНУ, {{result.price}} РУБ.</a>
</div>


{% endblock %}

structure/templates/structure/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="shortcut icon" type="image/x-icon" href="/media/favicon.ico">
        <title>{{ title }}</title>
        <meta charset="utf-8">
        <meta name ="viewport" content="width=device-width, initial-scale=1">

        {% block css%}

        {% endblock %}

    </head>
    <body>
        <nav class="sticky">
        <header id="header" class="header">
            <div class="container">
                <div class="nav-bar">

                    <a href="{% url 'structure:index' %}">
                        <img src="{% static '/source/images/main_logo.svg' %}" class= "logo" height="50"alt="Main Logo" loading="lazy"/>
                    </a>
                    <ul class = "menu">
                        <li>
                            <a class="neon-green" href="{% url 'structure:index' %}">FEATURED</a>
                            <span class="neon-skip">|</span>
                        </li>

                        <li>
                            <a class="neon-green" href="{% url 'structure:collections' %}">COLLECTIONS</a>
                            <span class="neon-skip">|</span>
                        </li>

                        {% if user.is_authenticated %}
                        <li>
                            <a class="neon-green" href="{% url 'structure:basket_view' %}">BASKET</a>
                        </li>
                        {% else %}
                        <li>
                            <a class="neon-green" href="{% url 'users:login' %}">BASKET</a>
                        </li>
                        {% endif %}
                    </ul>

                {% if user.is_authenticated %}
                <li>
                    <a class="neon-green-right" href="{% url 'users:profile' user.id %}">{{ user.username }}</a>
                </li>
                {% else %}
                <li>
                    <a class="neon-green-right" href="{% url 'users:login' %}">LOG_IN</a>
                </li>
                {% endif %}

                <a class = "switcher" href="{% url 'structure:bio' %}">
                    <img
                    src="{% static 'source/images/united-kingdom-uk-svgrepo-com.svg' %}"
                    height="50"
                    alt="Main Logo"
                    loading="lazy"
                  />
                </a>

            </div>

            </div>
        </div>
        <hr width="100%" color="#00F6BB" size="3px">
    </header>
</nav>


        <selection>
            {% block content %}
        {% endblock %}
        </selection>

    <footer id = "footer" class = "footer">
        <hr width="100%" color="#00F6BB" size="3px">
        
        <div class="container">
            <div class="jumper">
                <ul class="years">
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2023' %}">2023</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2022' %}">2022</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2021' %}">2021</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2020' %}">2020</a>
                    </li>
                </ul>
                <ul class="collections">
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='CRXNGE_BAR' %}">CRXNGE_BAR</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='ACADEMIC' %}">ACADEMIC</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='PORTFOLIO' %}">PORTFOLIO</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='FREEDOM' %}">FREEDOM</a>
                    </li>
                </ul>

            </div>
        </div>
        <hr width="100%" color="#00F6BB" size="3px">
        <div class="credits">
            <span>Soya Mariya</span>
            <br>
            <span>2024</span>
            <br>

        </div>
    </footer>


    <button id="back-to-top" onclick="scrollToTop()">Back to Top</button>

    <script>
        function scrollToTop() {
            window.scrollTo({top:0, behavior: 'smooth'})
        }

        window.onscroll = function () {
            var button = document.getElementById('back-to-top');
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                button.style.display = 'block';
            } else {
                button.style.display = 'none';
            }
        };
    </script>


    </body>
</html>

structure/templates/structure/basket.html
{% extends 'structure/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <style>
        /* Стили для контейнера товара */
        .collection-card {
            border-radius: 12px;
            background-color: #2c2c2c; /* Темно-серый фон */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
            transition: transform 0.3s ease;
            padding: 20px;
            margin-bottom: 20px;
            max-width: 350px; /* Увеличен контейнер */
            font-family: 'neon-green', sans-serif; /* Использован стиль шрифта neon-green */
        }

        .collection-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        }

        .card-header {
            background-color: #34495e;
            border-radius: 12px 12px 0 0;
            padding: 15px;
        }

        .card-body {
            color: #fff;
            padding: 20px;
        }

        .card-header h4 {
            font-family: 'neon-green', sans-serif;
            color: #00F6BB;
        }

        .helvetic-pale {
            font-family: 'Helvetica', sans-serif;
            color: #bdc3c7;
        }

        /* Стили для общей суммы корзины */
        .total-summary {
            font-size: 20px;
            font-weight: bold;
            color: #fff;
            margin-top: 30px;
            text-align: center;
            font-family: 'Helvetica', sans-serif;
        }

        .total-summary strong {
            color: #00F6BB;
        }

        /* Стиль для кнопки оплаты */
        .btn-payment {
            display: inline-block;
            padding: 14px 40px;
            background-color: #28a745; /* Зеленый для кнопки оплаты */
            color: #fff;
            text-align: center;
            border-radius: 8px;
            font-size: 18px;
            transition: all 0.3s ease;
            margin-top: 20px;
            font-family: 'Helvetica', sans-serif;
        }

        .btn-payment:hover {
            background-color: #218838;
            transform: translateY(-2px); /* Эффект поднятия */
        }

        .btn-payment:active {
            background-color: #1e7e34;
            transform: translateY(0);
        }

        /* Адаптивность */
        @media (max-width: 768px) {
            .total-summary {
                font-size: 18px;
            }

            .btn-payment {
                width: 100%;
                padding: 16px;
            }
        }
    </style>
{% endblock %}

{% block content %}
<main class="container">
    <section>
        <ul class="collections-container">
            {% if baskets %}
                {% for basket in baskets %}
                    <li class="collection-card card mb-4">
                        <div class="card-header text-light">
                            <h4 class="neon-green">{{ basket.product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <p class="helvetic-pale">Цена: {{ basket.sum }} р.</p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </section>

        <div class="total-summary">
            <strong>Total items:</strong> {{ baskets.total_quantity }} pcs <br>
            <strong>Total sum:</strong> {{ baskets.total_sum }} ₽
            <hr width="50%" color="#00F6BB" size="2px">

            <!-- Стилизованная кнопка оплаты, по центру -->
            <div>
                <a href="{% url 'order:order_view' %}" class="neon-green">
                    Pay
                </a>
            </div>
        </div>

    {% else %}
        <h1 class="neon-green" style="text-align: center;">Basket is empty</h1>
    {% endif %}
</main>
{% endblock %}

structure/templates/structure/bio.html
{% extends 'structure/base.html' %}
{% load static %}

{% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% endblock %}

{% block content %}
<div class="single-art-page">
            <img src="{% static '/source/images/eyes.png' %}" style="width: auto">
            <a class="helvetic-pale">UNDER CONSTRUCTION...</a>
</div>

{% endblock %}

structure/templates/structure/collections.html
{% extends 'structure/base.html' %}
{% load static %}

{% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% endblock %}

{% block content %}
<div class="collections-container">
    {% for collection in collections %}
    <div class="collection-card">
        <img src="{{ collection.image.url }}" class="collection-img" alt="">
        <div class="fading-text">
            <a class="barcode-pale" href="{% url 'structure:universal_collect' collection_name=collection.name %}">{{collection.name}}</a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

structure/templates/structure/draft.html
.artwork-grid-container {
  width: 900px;
  margin: 0 auto;
  display: inline-flex;
}

.column {
  width: 300px;
}

.art-container {
  width: 300px;
}

<div class="artwork-grid-container">
    <div class="column">
        {% for art1 in artworks %}
        <div class="art-container">
           <img href="{{art1.image.url }}">
        </div>
        {% endfor %}
    </div>
     <div class="column">
        {% for art2 in artworks %}
         <div class="art-container">
           <img href="{{art2.image.url }}">
        </div>
        {% endfor %}
    </div>
     <div class="column">
        {% for art3 in artworks %}
         <div class="art-container">
           <img href="{{art3.image.url }}">
        </div>
        {% endfor %}
    </div>
</div>

structure/templates/structure/index.html
{% extends 'structure/base.html' %}
{% load static %}

{% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% endblock %}

{% block content %}
<div class="secondary">
    <div class="artwork-grid-container">
        <div class="column">
            {% for art1 in artworks1 %}
            <div class="art-container">
               <img src="{{art1.image.url }}">
                <div class="fading-text-i">
            <a class="helvetic-pale" href="{% url 'structure:artpiece' art_name=art1.name %}">{{art1.name}}</a>
        </div>
            </div>
            {% endfor %}
        </div>
         <div class="column">
            {% for art2 in artworks2 %}
             <div class="art-container">
               <img src="{{art2.image.url }}">
                  <div class="fading-text-i">
            <a class="helvetic-pale" href="{% url 'structure:artpiece' art_name=art2.name %}">{{art2.name}}</a>
        </div>
            </div>
            {% endfor %}
        </div>
         <div class="column">
            {% for art3 in artworks3 %}
             <div class="art-container">
               <img src="{{art3.image.url }}">
                  <div class="fading-text-i">
            <a class="helvetic-pale" href="{% url 'structure:artpiece' art_name=art3.name %}">{{art3.name}}</a>
        </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

structure/templates/structure/universal_collect.html
{% extends 'structure/base.html' %}
{% load static %}

{% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% endblock %}

{% block content %}
    <div class="filter-container">
        {% for artwork in result %}
        <div class="filter-card">
            <img src="{{ artwork.image.url }}" class="filter-img" alt="">
            <div class="fading-text-f">
                <a class="helvetic-pale" href="{% url 'structure:artpiece' art_name=artwork.name %}">{{artwork.name}}</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

structure/templates/structure/universal_year.html
{% extends 'structure/base.html' %}
{% load static %}

{% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% endblock %}

{% block content %}
    <div class="filter-container">
        {% for artwork in result %}
        <div class="filter-card">
            <img src="{{ artwork.image.url }}" class="filter-img" alt="">
            <div class="fading-text-f">
                <a class="helvetic-pale" href="#">{{artwork.name}}</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}