Vishnya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from orders.views import my_webhook_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("structure.urls", namespace='structure')),
    path('users/', include("users.urls", namespace='users')),
    path('orders/', include("orders.urls", namespace='orders')),
    path('webhook/yookassa/', my_webhook_handler, name='webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import OrderView, SuccessTemplateView, CancelTemplateView, OrderListView, order_remove, receipt_list_view

app_name = 'order'
urlpatterns = [
    path('', OrderView.as_view(), name='order_view'),
    path('success/', SuccessTemplateView.as_view(), name='success_order'),
    path('canсel/', CancelTemplateView.as_view(), name='cancel_order'),
    path('list/', OrderListView.as_view(), name='list_order'),
    path('list/remove/<int:id>', order_remove, name='order_remove'),
    path('receipt/<int:id>', receipt_list_view, name='receipt'),
]

structure/urls.py
from django.urls import path
from structure.views import *

app_name = 'structure'
urlpatterns = [
    path('', index, name='index'),
    path('collections/', collections, name='collections'),
    path('sub_collection/<str:collection_name>/', universal_collect, name='universal_collect'),
    path('by_year/<str:year_name>/',universal_year, name='universal_year'),
    path('art_instance/<str:art_name>/', artpiece, name='artpiece'),
    path('about/', bio, name='bio'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/view/', basket_view, name='basket_view'),
    path('baskets/remove/<int:id>/', basket_remove, name='basket_remove'),
]

users/urls.py
from users.views import UserRegistrationView, UserLoginView, logout_view, UserProfileView
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',
        blank=True,
        help_text=('The groups this user belongs to. A user will get all permissions '
                   'granted to each of their groups.'),
        verbose_name=('groups'),
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',
        blank=True,
        help_text=('Specific permissions for this user.'),
        verbose_name=('user permissions'),
    )

    user_address = models.CharField(max_length=128, null=True, blank=True)
    email = models.EmailField(unique=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите почту'}))
    user_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'user_address', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите почту'}))
    user_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес'}))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'user_address')

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from users.forms import UserRegistrationForm, UserLoginForm, UserProfileForm
from users.models import User


class UserRegistrationView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Поздравляем! Вы успешно зарегестрировались!'

    def get_context_data(self, **kwargs):
        context = super(UserRegistrationView, self).get_context_data(**kwargs)
        context['title'] = 'Страница Регистрации'
        return context


class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('structure:index')


def logout_view(request):
    logout(request)
    form = UserLoginForm
    return render(request, 'users/login.html', {'form': form})


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['title'] = 'Личный кабинет'
        return context

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'pk': self.object.pk})

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="shortcut icon" type="image/x-icon" href="/media/favicon.ico">
        <title>{{ title }}</title>
        <meta charset="utf-8">
        <meta name ="viewport" content="width=device-width, initial-scale=1">

        {% block css%}

        {% endblock %}

    </head>
    <body>
        <nav class="sticky">
        <header id="header" class="header">
            <div class="container">
                <div class="nav-bar">

                    <a href="{% url 'structure:index' %}">
                        <img src="{% static '/source/images/main_logo.svg' %}" class= "logo" height="50"alt="Main Logo" loading="lazy"/>
                    </a>
                    <ul class = "menu">
                        <li>
                            <a class="neon-green" href="{% url 'structure:index' %}">FEATURED</a>
                            <span class="neon-skip">|</span>
                        </li>

                        <li>
                            <a class="neon-green" href="{% url 'structure:collections' %}">COLLECTIONS</a>
                            <span class="neon-skip">|</span>
                        </li>

                        {% if user.is_authenticated %}
                        <li>
                            <a class="neon-green" href="{% url 'structure:basket_view' %}">BASKET</a>
                        </li>
                        {% else %}
                        <li>
                            <a class="neon-green" href="{% url 'users:login' %}">BASKET</a>
                        </li>
                        {% endif %}
                    </ul>

                {% if user.is_authenticated %}
                <li>
                    <a class="neon-green-right" href="{% url 'users:profile' user.id %}">{{ user.username }}</a>
                </li>
                {% else %}
                <li>
                    <a class="neon-green-right" href="{% url 'users:login' %}">LOG_IN</a>
                </li>
                {% endif %}

                <a class = "switcher" href="{% url 'structure:bio' %}">
                    <img
                    src="{% static 'source/images/united-kingdom-uk-svgrepo-com.svg' %}"
                    height="50"
                    alt="Main Logo"
                    loading="lazy"
                  />
                </a>

            </div>

            </div>
        </div>
        <hr width="100%" color="#00F6BB" size="3px">
    </header>
</nav>


        <selection>
            {% block content %}
        {% endblock %}
        </selection>

    <footer id = "footer" class = "footer">
        <hr width="100%" color="#00F6BB" size="3px">

        <div class="container">
            <div class="jumper">
                <ul class="years">
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2023' %}">2023</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2022' %}">2022</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2021' %}">2021</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_year' year_name='2020' %}">2020</a>
                    </li>
                </ul>
                <ul class="collections">
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='CRXNGE_BAR' %}">CRXNGE_BAR</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='ACADEMIC' %}">ACADEMIC</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='PORTFOLIO' %}">PORTFOLIO</a>
                    </li>
                    <li>
                        <a href="{% url 'structure:universal_collect' collection_name='FREEDOM' %}">FREEDOM</a>
                    </li>
                </ul>

            </div>
        </div>
        <hr width="100%" color="#00F6BB" size="3px">
        <div class="credits">
            <span>Soya Mariya</span>
            <br>
            <span>2024</span>
            <br>

        </div>
    </footer>


    <button id="back-to-top" onclick="scrollToTop()">Back to Top</button>

    <script>
        function scrollToTop() {
            window.scrollTo({top:0, behavior: 'smooth'})
        }

        window.onscroll = function () {
            var button = document.getElementById('back-to-top');
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                button.style.display = 'block';
            } else {
                button.style.display = 'none';
            }
        };
    </script>


    </body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <style>
        /* Стили для центрирования формы */
        .container-form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: black; /* Цвет фона формы */
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        /* Стили для элементов формы */
        .form-group input {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border-radius: 5px;
            border: 1px solid black;
            margin-top: 5px;
        }

        .form-group label {
            font-size: 16px;
            font-weight: bold;
        }

        .btn-primary {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            background-color: #4CAF50; /* Зеленый фон */
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: #45a049; /* Темно-зеленый при наведении */
        }

        /* Стили для текста и ссылок */
        .helvetic-pale {
            color: #777;
            font-size: 14px;
        }

        .helvetic-pale a {
            color: #4CAF50; /* Зеленый цвет для ссылки */
            text-decoration: none;
        }

        .helvetic-pale a:hover {
            text-decoration: underline;
        }

    </style>
    <div class="container-form">
        <h1 class="neon-green">LOG IN</h1>
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
                {{ form.username.errors }}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password }}
                {{ form.password.errors }}
            </div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
        <p class="helvetic-pale">Нет аккаунта? <a class="underline" href="{% url 'users:registration' %}">Зарегистрироваться</a></p>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <style>
        /* Стили для центрирования формы */
        .container-form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: black; /* Цвет фона формы */
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        /* Стили для элементов формы */
        .form-group input {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border-radius: 5px;
            border: 1px solid black;
            margin-top: 5px;
        }

        .form-group label {
            font-size: 16px;
            font-weight: bold;
        }

        .btn-primary {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            background-color: #4CAF50; /* Зеленый фон */
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: #45a049; /* Темно-зеленый при наведении */
        }

        /* Стили для текста и ссылок */
        .helvetic-pale {
            color: #777;
            font-size: 14px;
        }

        .helvetic-pale a {
            color: #4CAF50; /* Зеленый цвет для ссылки */
            text-decoration: none;
        }

        .helvetic-pale a:hover {
            text-decoration: underline;
        }

    </style>
<div class="container-form">
    <h1 class="neon-green">USER PROFILE</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
            {{ form.first_name.errors }}
        </div>
        <div class="form-group">
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
            {{ form.last_name.errors }}
        </div>
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="form-group">
            {{ form.user_address.label_tag }}
            {{ form.user_address }}
            {{ form.user_address.errors }}
        </div>
        <button type="submit" class="btn btn-primary">UPDATE PROFILE</button>
    </form>
    <hr width="100%" color="#00F6BB" size="2px">
    <div>
        <a href="{% url 'users:logout' %}" class="neon-green">LOGOUT</a>
    </div>
    <hr width="100%" color="#00F6BB" size="2px">
    <div>
        <a href="{% url 'order:list_order' %}" class="neon-green">ORDER LIST</a>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "users/base.html" %}

{% load static %}

{% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <style>
        /* Стили для центрирования формы */
        .container-form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: black; /* Цвет фона формы */
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        /* Стили для элементов формы */
        .form-group input {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border-radius: 5px;
            border: 1px solid black;
            margin-top: 5px;
        }

        .form-group label {
            font-size: 16px;
            font-weight: bold;
        }

        .btn-primary {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            background-color: #4CAF50; /* Зеленый фон */
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: #45a049; /* Темно-зеленый при наведении */
        }

        /* Стили для текста и ссылок */
        .helvetic-pale {
            color: #777;
            font-size: 14px;
        }

        .helvetic-pale a {
            color: #4CAF50; /* Зеленый цвет для ссылки */
            text-decoration: none;
        }

        .helvetic-pale a:hover {
            text-decoration: underline;
        }

    </style>
<div class="container-form">
    <h1 class="neon-green">REGISTER</h1>
    <form action="{% url 'users:registration' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
            {{ form.first_name.errors }}
        </div>
        <div class="form-group">
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
            {{ form.last_name.errors }}
        </div>
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="form-group">
            {{ form.user_address.label_tag }}
            {{ form.user_address }}
            {{ form.user_address.errors }}
        </div>
        <div class="form-group">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
            {{ form.password1.errors }}
        </div>
        <div class="form-group">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
            {{ form.password2.errors }}
        </div>
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
</div>
{% endblock %}